# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ath-tools = {
    pname = "ath-tools";
    version = "f4901c23602cb5b5d86202f3f7f4a62323fdbc82";
    src = fetchgit {
      url = "https://github.com/qca/qca-swiss-army-knife.git";
      rev = "f4901c23602cb5b5d86202f3f7f4a62323fdbc82";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8kRhGM0Q/0GLMNGztiUVnyRYLAFMx/w6prgWJ3EIU1c=";
    };
    date = "2026-01-09";
  };
  base24-schemes = {
    pname = "base24-schemes";
    version = "7725e097895102ca2949c7a553b54dca0b2e2667";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "7725e097895102ca2949c7a553b54dca0b2e2667";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lOw77YOBM6HNuWcLL4Qugn+vr4RxMKV8FgXqFlnyLIo=";
    };
    date = "2026-02-17";
  };
  claude-code-acp = {
    pname = "claude-code-acp";
    version = "v0.18.0";
    src = fetchFromGitHub {
      owner = "zed-industries";
      repo = "claude-code-acp";
      rev = "v0.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-KZg9z8cyMqMHOfATaT2gcbp0+HkqzecQvAVeHN+bCYg=";
    };
  };
  flightcore = {
    pname = "flightcore";
    version = "v3.2.0";
    src = fetchFromGitHub {
      owner = "R2NorthstarTools";
      repo = "FlightCore";
      rev = "v3.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-MFnW9cXFzqmdtC31r8cRcihV3NjGAC6+2/DnNVMheCI=";
    };
  };
  qebspil = {
    pname = "qebspil";
    version = "8e4d9e676a3b3afe136cda9b953a2139ff1a32d0";
    src = fetchgit {
      url = "https://github.com/stephan-gh/qebspil.git";
      rev = "8e4d9e676a3b3afe136cda9b953a2139ff1a32d0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kWUXzeYWNxGgmjt/p9yozrWc5ouUs0XXBRfiFMlu+QQ=";
    };
    date = "2025-10-25";
  };
  radare2-ghidra = {
    pname = "radare2-ghidra";
    version = "6.1.0";
    src = fetchFromGitHub {
      owner = "radareorg";
      repo = "r2ghidra";
      rev = "6.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-KmzS4Q39ztiGc8rnUqcx5tUXuTCK8WcQrFelKzvaOEw=";
    };
  };
  radare2-mcp = {
    pname = "radare2-mcp";
    version = "1.5.6";
    src = fetchFromGitHub {
      owner = "radareorg";
      repo = "radare2-mcp";
      rev = "1.5.6";
      fetchSubmodules = false;
      sha256 = "sha256-oR7+6djPmrEWpomqNPnw+ciEgXWsB/pmJPvpt37z21w=";
    };
  };
  slbounce = {
    pname = "slbounce";
    version = "v5";
    src = fetchFromGitHub {
      owner = "TravMurav";
      repo = "slbounce";
      rev = "v5";
      fetchSubmodules = false;
      sha256 = "sha256-w+0SKR0A/hcFU6iFEOgyG+vWwgAWF8h9D0/X7GSFm7w=";
    };
  };
}
