# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ath-tools = {
    pname = "ath-tools";
    version = "324903e86fbd30d601f404125da74b28d812be4b";
    src = fetchgit {
      url = "https://github.com/qca/qca-swiss-army-knife.git";
      rev = "324903e86fbd30d601f404125da74b28d812be4b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Gykx/uHPzbHPECtiCoRmo9YWxUpYc7Ky1lNBENLsRm4=";
    };
    date = "2026-04-15";
  };
  base24-schemes = {
    pname = "base24-schemes";
    version = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PDF0/wObw4nIsSBeXVYLsloXOiphXCgIdsrNcVXguKs=";
    };
    date = "2026-05-03";
  };
  claude-code-acp = {
    pname = "claude-code-acp";
    version = "v0.35.0";
    src = fetchFromGitHub {
      owner = "zed-industries";
      repo = "claude-code-acp";
      rev = "v0.35.0";
      fetchSubmodules = false;
      sha256 = "sha256-xb6D4J+EmbK5XCrZCyv1LWYdfmaNDcw7Hk4nHg76uAo=";
    };
  };
  flightcore = {
    pname = "flightcore";
    version = "v3.2.0";
    src = fetchFromGitHub {
      owner = "R2NorthstarTools";
      repo = "FlightCore";
      rev = "v3.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-MFnW9cXFzqmdtC31r8cRcihV3NjGAC6+2/DnNVMheCI=";
    };
  };
  grimoire = {
    pname = "grimoire";
    version = "v1.14.2";
    src = fetchFromGitHub {
      owner = "Slush97";
      repo = "grimoire";
      rev = "v1.14.2";
      fetchSubmodules = false;
      sha256 = "sha256-iRZF06kjmJJJOeiUpWm8T2REO/FSdpwc73dOXu6Xs9w=";
    };
  };
  neovide = {
    pname = "neovide";
    version = "8c48a699e201aa5559227a96d879b2f57192b354";
    src = fetchgit {
      url = "https://github.com/neovide/neovide.git";
      rev = "8c48a699e201aa5559227a96d879b2f57192b354";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ke8bM5o33s1h1fHY7Y10fYKpVwS3/pU7iOBpBOC0Dvw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Ke8bM5o33s1h1fHY7Y10fYKpVwS3_pU7iOBpBOC0Dvw=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-05-16";
  };
  qebspil = {
    pname = "qebspil";
    version = "8e4d9e676a3b3afe136cda9b953a2139ff1a32d0";
    src = fetchgit {
      url = "https://github.com/stephan-gh/qebspil.git";
      rev = "8e4d9e676a3b3afe136cda9b953a2139ff1a32d0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kWUXzeYWNxGgmjt/p9yozrWc5ouUs0XXBRfiFMlu+QQ=";
    };
    date = "2025-10-25";
  };
  radare2-ghidra = {
    pname = "radare2-ghidra";
    version = "6.1.4";
    src = fetchFromGitHub {
      owner = "radareorg";
      repo = "r2ghidra";
      rev = "6.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-uVMsONXethTq/BL9MBQkDP3iJ6t25PEnpeD/Y17dpxM=";
    };
  };
  radare2-mcp = {
    pname = "radare2-mcp";
    version = "1.8.0";
    src = fetchFromGitHub {
      owner = "radareorg";
      repo = "radare2-mcp";
      rev = "1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-1tV3mG1hEIcq18cHn5kS4n9ocVZsHQ5A4TCTA3OKzn8=";
    };
  };
  slbounce = {
    pname = "slbounce";
    version = "v5";
    src = fetchFromGitHub {
      owner = "TravMurav";
      repo = "slbounce";
      rev = "v5";
      fetchSubmodules = false;
      sha256 = "sha256-w+0SKR0A/hcFU6iFEOgyG+vWwgAWF8h9D0/X7GSFm7w=";
    };
  };
  vpkmerge = {
    pname = "vpkmerge";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "Slush97";
      repo = "vpkmerge";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-CaNyzN8kRtzKwIUAe1or6ZhcaZNeGCKNCkRUTK2f/H8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-CaNyzN8kRtzKwIUAe1or6ZhcaZNeGCKNCkRUTK2f_H8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
