# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  ath-tools = {
    pname = "ath-tools";
    version = "c8182015b0ec81da1d4c39841aca190deae77c2c";
    src = fetchgit {
      url = "https://github.com/qca/qca-swiss-army-knife.git";
      rev = "c8182015b0ec81da1d4c39841aca190deae77c2c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-Va845WLEyB+l7cpLIvYpvwOyMZuLKcb3Afqqs/cUSmI=";
    };
    date = "2026-03-03";
  };
  base24-schemes = {
    pname = "base24-schemes";
    version = "3e228732e93c107e8b65b8be30c36e5b3c507d95";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "3e228732e93c107e8b65b8be30c36e5b3c507d95";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-G34G4hri8H2XNwF0e15MFj3sjO8fTOphNk0WjBwnVew=";
    };
    date = "2026-04-12";
  };
  claude-code-acp = {
    pname = "claude-code-acp";
    version = "v0.26.0";
    src = fetchFromGitHub {
      owner = "zed-industries";
      repo = "claude-code-acp";
      rev = "v0.26.0";
      fetchSubmodules = false;
      sha256 = "sha256-2G8gjMCnk3W1I2+4sNsumL15ts9bLXAOMguCmwnzWSA=";
    };
  };
  flightcore = {
    pname = "flightcore";
    version = "v3.2.0";
    src = fetchFromGitHub {
      owner = "R2NorthstarTools";
      repo = "FlightCore";
      rev = "v3.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-MFnW9cXFzqmdtC31r8cRcihV3NjGAC6+2/DnNVMheCI=";
    };
  };
  neovide = {
    pname = "neovide";
    version = "nightly";
    src = fetchgit {
      url = "https://github.com/neovide/neovide.git";
      rev = "nightly";
      fetchSubmodules = true;
      deepClone = true;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-JBV939TEfG44w59iUJ3KgiCrQ9aCcjmPxu2uoBD/Ank=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-JBV939TEfG44w59iUJ3KgiCrQ9aCcjmPxu2uoBD_Ank=/Cargo.lock";
      outputHashes = {
      };
    };
  };
  qebspil = {
    pname = "qebspil";
    version = "8e4d9e676a3b3afe136cda9b953a2139ff1a32d0";
    src = fetchgit {
      url = "https://github.com/stephan-gh/qebspil.git";
      rev = "8e4d9e676a3b3afe136cda9b953a2139ff1a32d0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-kWUXzeYWNxGgmjt/p9yozrWc5ouUs0XXBRfiFMlu+QQ=";
    };
    date = "2025-10-25";
  };
  radare2-ghidra = {
    pname = "radare2-ghidra";
    version = "6.1.2";
    src = fetchFromGitHub {
      owner = "radareorg";
      repo = "r2ghidra";
      rev = "6.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-bGA7izBSvlwnD4BZXNucYS39BDdmo+49cY3o4LjIpYM=";
    };
  };
  radare2-mcp = {
    pname = "radare2-mcp";
    version = "1.7.2";
    src = fetchFromGitHub {
      owner = "radareorg";
      repo = "radare2-mcp";
      rev = "1.7.2";
      fetchSubmodules = false;
      sha256 = "sha256-ToSvRmgOyrmsFWjfwuDit5hLXYJQD7YKGoy2utkqUe0=";
    };
  };
  slbounce = {
    pname = "slbounce";
    version = "v5";
    src = fetchFromGitHub {
      owner = "TravMurav";
      repo = "slbounce";
      rev = "v5";
      fetchSubmodules = false;
      sha256 = "sha256-w+0SKR0A/hcFU6iFEOgyG+vWwgAWF8h9D0/X7GSFm7w=";
    };
  };
}
